"""
This type stub file was generated by cyright.
"""

from numpy import ndarray

class MovingAverage:
    def __init__(self, window: int, is_fast: bool) -> None: ...
    def initialize(self, values: ndarray) -> float:
        """
        Initializes the moving average with the given values.
        Values must be the length of the window.

        Must be called before any other methods.
        """
        ...

    def next(self, value: float) -> float:
        """
        Calculates the next value in the moving average without
        updating the internal state. Useful for plotting.
        """
        ...

    def update(self, value: float) -> float:
        """
        Calculates the next value in the moving average and
        updates the internal state.
        """
        ...

    def get_value(self) -> float:
        """
        Returns the current value of the moving average.
        """
        ...

    def get_values(self) -> ndarray:
        """
        Returns the values in the moving average as a numpy array.
        """
        ...

    def __len__(self):  # -> int:
        """
        Get the number of elements currently in the buffer.

        Returns:
            int: The current size of the buffer.
        """
        ...

    def __contains__(self, value: float):
        """
        Check if a value is present in the buffer.

        Parameters:
            value (float): The value to search for.

        Returns:
            bool: True if the value is in the buffer, False otherwise.
        """
        ...

    def __iter__(self):
        """
        Iterate over the elements in the buffer in order from oldest to newest.

        Yields:
            float: Each value in the buffer.
        """
        ...

    def __getitem__(self, idx: int):
        """
        Get the element at the given index.

        Parameters:
            idx (int): The index of the element to retrieve.

        Returns:
            float: The value at the specified index.

        Raises:
            IndexError: If the index is out of range.
        """
        ...
