"""
This type stub file was generated by cyright.
"""

from numpy import ndarray

from .base import MovingAverage

class ExponentialMovingAverage(MovingAverage):
    """
    The EMA uses exponentially increasing weights 3/(N+1), where N is the window size.

    This can be overridden in the `alpha` parameter.
    """
    def __init__(self, window: int, is_fast: bool = ..., alpha: float = ...) -> None:
        ...
    
    def initialize(self, values: ndarray) -> float:
        ...
    
    def next(self, new_val: float) -> float:
        ...
    
    def update(self, new_val: float) -> float:
        ...
    


