"""
This type stub file was generated by cyright.
"""

from numpy import ndarray

from .base import MovingAverage

class TimeExponentialMovingAverage(MovingAverage):
    """
    The TEMA uses variable weights based on the time of entry,
    with a

    Implementation
    --------------
    - We compute `alpha = 1.0 - exp(self.lam * (self.time - t))`
      whenever we do an update.
    - Then `self.value = alpha * input + (1 - alpha) * self.value`.
    - We store `self.time = t`.
    - If not ready, we simply set `self.value = input; self.time = t; ready = True`.
    """
    def __init__(
        self, window: int, fast: bool = ..., half_life_s: float = ...
    ) -> None: ...
    def initialize(self, values: ndarray) -> float: ...
    def next(self, new_val: float) -> float: ...
    def update(self, new_val: float) -> float: ...
