"""
This type stub file was generated by cyright.
"""

from numpy import ndarray

from .base import MovingAverage

class WeightedMovingAverage(MovingAverage):
    """
    The WMA uses linearly increasing weights from 1 to N, where N is the window size.
    """
    def __init__(self, window: int, fast: bool = ...) -> None: ...
    def initialize(self, values: ndarray) -> float: ...
    def next(self, new_val: float) -> float: ...
    def update(self, new_val: float) -> float: ...
