"""
This type stub file was generated by cyright.
"""

from typing import Any

from .base import BaseCandles

class PriceCandles(BaseCandles):
    """
    Candle aggregator that creates new candles based on price movement.

    A new candle is created when the price moves by a specified amount from the opening price.
    """
    def __init__(self, price_bucket: float, num_candles: int) -> None:
        """
        Initialize the price-based candle aggregator.

        Args:
            price_bucket (double): Price movement threshold that triggers a new candle.
            num_candles (Py_ssize_t): Maximum number of candles to store.
        """
        ...

    def process_trade(self, time: float, is_buy: bool, px: float, sz: float) -> Any:
        """
        Process a single trade tick, updating the current candle.

        Creates a new candle when the price moves by price_bucket amount from the opening price.

        Args:
            time (double): The timestamp of the trade in milliseconds.
            is_buy (bint): True if it's a buy trade, False if it's a sell trade.
            px (double): The trade price.
            sz (double): The trade size (volume).
        """
        ...
