"""
This type stub file was generated by cyright.
"""

from typing import Any

from .base import BaseCandles

class TimeCandles(BaseCandles):
    """
    Candle aggregator that creates new candles based on a fixed time interval.

    A new candle is created when the specified time interval has elapsed.
    """
    def __init__(self, secs_per_bucket: float, num_candles: int) -> None:
        """
        Initialize the time-based candle aggregator.

        Args:
            secs_per_bucket (double): Time interval per candle in seconds.
            num_candles (Py_ssize_t): Maximum number of candles to store.
        """
        ...

    def process_trade(self, time: float, is_buy: bool, px: float, sz: float) -> Any:
        """
        Process a single trade tick, updating the current candle.

        Creates a new candle when the time interval has elapsed.

        Args:
            time (double): The timestamp of the trade in milliseconds.
            is_buy (bint): True if it's a buy trade, False if it's a sell trade.
            px (double): The trade price.
            sz (double): The trade size (volume).
        """
        ...
