"""
This type stub file was generated by cyright.
"""

from typing import Any
from numpy import ndarray

from .base import BaseCandles

class VolumeCandles(BaseCandles):
    """
    Candle aggregator that creates new candles based on a fixed volume threshold.
    
    A new candle is created when the specified volume threshold is reached.
    """
    def __init__(self, volume_per_bucket: int, num_candles: int) -> None:
        """
        Initialize the volume-based candle aggregator.
        
        Args:
            volume_per_bucket (Py_ssize_t): Volume threshold per candle.
            num_candles (Py_ssize_t): Maximum number of candles to store.
        """
        ...
    
    def process_trade(self, time: float, is_buy: bool, px: float, sz: float) -> Any:
        """
        Process a single trade tick, updating the current candle.
        
        Creates a new candle when the volume threshold is reached.
        
        Args:
            time (double): The timestamp of the trade in milliseconds.
            is_buy (bint): True if it's a buy trade, False if it's a sell trade.
            px (double): The trade price.
            sz (double): The trade size (volume).
        """
        ...
    


