"""
This type stub file was generated by cyright.
"""

def time_s() -> float:
    """
    Returns the current wall-clock time in seconds (float).
    """
    ...

def time_ms() -> float:
    """
    Returns the current wall-clock time in milliseconds (float).
    """
    ...

def time_us() -> float:
    """
    Returns the current wall-clock time in microseconds (float).
    """
    ...

def time_ns() -> int:
    """
    Returns the current wall-clock time in nanoseconds (float).
    """
    ...

def iso8601_to_unix(timestamp: str) -> float:
    """
    Converts an ISO 8601 formatted timestamp to a Unix timestamp.

    Parameters:
        timestamp (str) : An ISO 8601 formatted date-time string.

    Returns:
        float: The Unix timestamp corresponding to the provided ISO 8601 date-time.
    """
    ...

def unix_to_iso8601(timestamp: float) -> str:
    """
    Converts a Unix timestamp to an ISO 8601 formatted timestamp.

    This could use a faster implementation, will come in the future.
    For now, this works and is stable (stdlib impl).

    Parameters:
        timestamp (float) : The Unix timestamp to convert.

    Returns:
        str: The ISO 8601 formatted timestamp.
    """
    ...

def time_iso8601() -> str:
    """
    Returns the current UTC time as 'YYYY-MM-DDTHH:MM:SS.fffZ'.

    Returns:
        str: The formatted date/time.
    """
    ...

