"""
This type stub file was generated by cyright.
"""

def time_s() -> int:
    """
    Returns the current wall-clock time in seconds (float).
    
    Returns:
        float: Current time in seconds since Unix epoch.
        
    Raises:
        RuntimeError: If system clock access fails.
    """
    ...

def time_ms() -> float:
    """
    Returns the current wall-clock time in milliseconds (float).
    
    Returns:
        float: Current time in milliseconds since Unix epoch.
        
    Raises:
        RuntimeError: If system clock access fails.
    """
    ...

def time_us() -> float:
    """
    Returns the current wall-clock time in microseconds (float).
    
    Returns:
        float: Current time in microseconds since Unix epoch.
        
    Raises:
        RuntimeError: If system clock access fails.
    """
    ...

def time_ns() -> int:
    """
    Returns the current wall-clock time in nanoseconds (int64).
    
    Returns:
        int64_t: Current time in nanoseconds since Unix epoch.
        
    Raises:
        RuntimeError: If system clock access fails.
    """
    ...

def iso8601_to_unix(timestamp: str) -> float:
    """
    Converts an ISO 8601 formatted timestamp to a Unix timestamp.

    Args:
        timestamp (str): An ISO 8601 formatted date-time string.

    Returns:
        float: The Unix timestamp corresponding to the provided ISO 8601 date-time.
        
    Raises:
        ValueError: If the timestamp format is invalid.
    """
    ...

def time_iso8601(timestamp: float = ...) -> str:
    """
    Returns an ISO 8601 formatted timestamp.
    
    Args:
        timestamp (float, optional): Unix timestamp to format. If 0.0 (default),
            uses the current time with optimized manual date arithmetic for 
            maximum performance.

    Returns:
        str: The formatted timestamp as 'YYYY-MM-DDTHH:MM:SS.fffZ'.
        
    Raises:
        MemoryError: If memory allocation fails.
        RuntimeError: If system clock access fails.
        ValueError: If timestamp is invalid.
    """
    ...

