"""
This type stub file was generated by cyright.
"""

from numpy import ndarray

class Rounder:
    """
    Provides rounding operations on prices and sizes according to specified tick and lot sizes.
    """
    def bid(self, px: float) -> float:
        """
        Round a price down to the nearest tick size multiple.

        Args:
            px (float): The price to be rounded down.

        Returns:
            float: The rounded (bid) price.
        """
        ...

    def ask(self, px: float) -> float:
        """
        Round a price up to the nearest tick size multiple.

        Args:
            px (float): The price to be rounded up.

        Returns:
            float: The rounded (ask) price.
        """
        ...

    def size(self, size: float) -> float:
        """
        Round a size down to the nearest lot size multiple.

        Args:
            size (float): The size to be rounded down.

        Returns:
            float: The rounded size.
        """
        ...

    def bids(self, pxs: ndarray) -> ndarray:
        """
        Round an array of prices down to the nearest tick size multiple (bids).

        Args:
            pxs (np.ndarray): An array of prices to be rounded.

        Returns:
            np.ndarray: A new array containing rounded bid prices.
        """
        ...

    def asks(self, pxs: ndarray) -> ndarray:
        """
        Round an array of prices up to the nearest tick size multiple (asks).

        Args:
            pxs (np.ndarray): An array of prices to be rounded.

        Returns:
            np.ndarray: A new array containing rounded ask prices.
        """
        ...

    def sizes(self, sizes: ndarray) -> ndarray:
        """
        Round an array of sizes down to the nearest lot size multiple.

        Args:
            sizes (np.ndarray): An array of sizes to be rounded.

        Returns:
            np.ndarray: A new array containing rounded sizes.
        """
        ...
