"""
This type stub file was generated by cyright.
"""

from mm_toolbox.logging.advanced.structs import LogLevel

class LoggerConfig:
    def __init__(
        self,
        base_level: LogLevel = ...,
        do_stout: bool = ...,
        str_format: str = ...,
        path: str = ...,
        flush_interval_s: float = ...,
    ) -> None:
        """
        Initialize the LoggerConfig with transport, path, and format settings.

        Args:
            base_level (LogLevel): The minimum log level to process. Defaults to `LogLevel.INFO`.
            do_stout (bool): Whether to print to stdout. Defaults to False.
            str_format (str): The format string for log messages, similar to Python's default logger.
                Supports standard format placeholders like %(asctime)s, %(name)s, %(levelname)s,
                and %(message)s. Defaults to '%(asctime)s [%(levelname)s] %(name)s - %(message)s'.
                Must contain at least %(message)s to be valid.
            path (str): The connection path for the transport protocol. Must follow the format
                required by the selected transport protocol. Defaults to 'ipc:///tmp/hft_logger'.
            flush_interval_s (float): Timeout in seconds for log messages. Defaults to 1.0.
        """
        ...
