"""
This type stub file was generated by cyright.
"""

class LoggerConfig:
    def __init__(self, base_level: int = ..., do_stout: bool = ..., str_format: str = ..., path: str = ..., log_timeout_s: float = ..., log_buffer_size: int = ..., data_timeout_s: float = ..., data_buffer_size: int = ...) -> None:
        """
        Initialize the LoggerConfig with transport, path, and format settings.
        
        Args:
            base_level (int): The minimum log level to process. Defaults to `LogLevel.INFO`.
            do_stout (bool): Whether to print to stdout. Defaults to False.
            str_format (str): The format string for log messages, similar to Python's default logger.
                Supports standard format placeholders like %(asctime)s, %(name)s, %(levelname)s, 
                and %(message)s. Defaults to '%(asctime)s [%(levelname)s] %(name)s - %(message)s'.
                Must contain at least %(message)s to be valid.
            path (str): The connection path for the transport protocol. Must follow the format
                required by the selected transport protocol. Defaults to 'ipc:///tmp/hft_logger'.
            log_timeout_s (float): Timeout in seconds for log messages. Defaults to 2.0.
            log_buffer_size (int): The maximum number of log messages this buffer can hold. Defaults to 1000.
            data_timeout_s (float): Timeout in seconds for data messages. Defaults to 5.0.
            data_buffer_size (int): The maximum number of data messages this buffer can hold. Defaults to 1000.
        Raises:
            ValueError: If the transport is not one of the supported types, if the path
                does not follow the required format for the selected transport, or if the
                format string does not contain the required %(message)s placeholder.
        """
        ...
    


