"""
This type stub file was generated by cyright.
"""
from enum import IntEnum

# For some reason, cyright cannot detect cpdef enums' equivalence to 
# normal python enums. It is pasted below for type hint reasons.
class LogLevel(IntEnum):
    TRACE = 0
    DEBUG = 1
    INFO = 2
    WARNING = 3
    ERROR = 4
    CRITICAL = 5
    
class LogBatch:
    ...
