"""
This type stub file was generated by cyright.
"""

import msgspec
from enum import IntEnum
from typing import Union, T

class LogLevel(IntEnum):
    TRACE = 0x0
    DEBUG = 0x1
    INFO = 0x2
    WARNING = 0x3
    ERROR = 0x4
    CRITICAL = 0x5


class LogMessage(msgspec.Struct, kw_only=True, tag=True, gc=False):
    time: Union[int, float]
    level: int
    msg: LogMessage
    ...


class LogMessageBatch(msgspec.Struct, kw_only=True, tag=True, gc=False):
    system: dict[str, str]
    name: bytes
    time: Union[int, float]
    size: int
    data: list[LogMessage]
    ...


class DataMessage(msgspec.Struct, kw_only=True, tag=True, gc=False):
    time: Union[int, float]
    msg: msgspec.Struct
    ...


class DataMessageBatch(msgspec.Struct, kw_only=True, tag=True, gc=False):
    system: dict[str, str]
    name: bytes
    time: Union[int, float]
    size: int
    data: list[T]
    ...


LogLevelMap: dict[int, str] = ...
def log_level_to_str(level: int) -> str:
    """
    Convert a LogLevel enum to its corresponding string representation.

    Rather than using LogLevelMap, this function is faster as comparing 
    int<>int in Cython compiles to switch-case statements under the hood.

    Args:
        level (int): The LogLevel enum value to convert.

    Returns:
        str: The string representation of the LogLevel enum value.
    """
    ...

class MessageBuffer:
    """
    A fixed-size buffer of LogMessage structs for efficient batch storage and encoding.
    """
    ...


