"""
This type stub file was generated by cyright.
"""

from typing import Any
from mm_toolbox.logging.advanced.structs import LogLevel
from mm_toolbox.logging.advanced.config import LoggerConfig

class WorkerLogger:
    """
    A lightweight worker logger that sends log messages and data to the master logger.

    This class manages two internal buffers—one for log messages and one for data messages—
    and pushes them to the master logger when full or upon request.
    """
    def _timed_operations(self) -> Any:
        """
        Background thread that periodically sends heartbeat messages to the master logger.
        """
        ...

    def set_log_level(self, level: LogLevel) -> Any:
        """
        Modify the logger's base log level at runtime.

        Args:
            level (LogLevel): The new base log level.
        """
        ...

    def trace(self, msg_str: str = ..., msg_bytes: bytes = ...) -> Any:
        """
        Send a trace-level log message.

        Args:
            msg_str (str, optional): The log message text as a string.
            msg_bytes (bytes, optional): The log message text as bytes.
        """
        ...

    def debug(self, msg_str: str = ..., msg_bytes: bytes = ...) -> Any:
        """
        Send a debug-level log message.

        Args:
            msg_str (str, optional): The log message text as a string.
            msg_bytes (bytes, optional): The log message text as bytes.
        """
        ...

    def info(self, msg_str: str = ..., msg_bytes: bytes = ...) -> Any:
        """
        Send an info-level log message.

        Args:
            msg_str (str, optional): The log message text as a string.
            msg_bytes (bytes, optional): The log message text as bytes.
        """
        ...

    def warning(self, msg_str: str = ..., msg_bytes: bytes = ...) -> Any:
        """
        Send a warning-level log message.

        Args:
            msg_str (str, optional): The log message text as a string.
            msg_bytes (bytes, optional): The log message text as bytes.
        """
        ...

    def error(self, msg_str: str = ..., msg_bytes: bytes = ...) -> Any:
        """
        Send an error-level log message.

        Args:
            msg_str (str, optional): The log message text as a string.
            msg_bytes (bytes, optional): The log message text as bytes.
        """
        ...

    def critical(self, msg_str: str = ..., msg_bytes: bytes = ...) -> Any:
        """
        Send a critical-level log message.

        Args:
            msg_str (str, optional): The log message text as a string.
            msg_bytes (bytes, optional): The log message text as bytes.
        """
        ...

    def shutdown(self) -> Any:
        """
        Flush any remaining messages and shuts down the worker logger.

        This method drains the log buffer, sending any remaining items to the master logger,
        and then stops the connection.

        Warning:
            After calling `shutdown()`, this logger should not be used again.
        """
        ...

    def is_running(self) -> bool:
        """
        Check if the logger is running.
        """
        ...

    def get_name(self) -> str:
        """
        Get the name of the logger.
        """
        ...

    def get_config(self) -> LoggerConfig:
        """
        Get the configuration of the logger.
        """
        ...
