"""
This type stub file was generated by cyright.
"""

from typing import Any

from .structs import LogLevel
from .config import LoggerConfig

class WorkerLogger:
    """
    A lightweight worker logger that sends log messages and data to the master logger.

    This class manages two internal buffers—one for log messages and one for data messages—
    and pushes them to the master logger when full or upon request.
    """
    def __init__(self, config: LoggerConfig = ..., name: str = ...) -> None:
        """
        Initialize the WorkerLogger.

        Args:
            config (LoggerConfig): Configuration details for connecting to the master logger.
            name (str, optional): The name of the worker to attach to log messages. 
                Defaults to an empty string.
        """
        ...
    
    def set_format(self, format_string: str) -> Any:
        """
        Modify the format string for log messages in runtime.

        Args:
            format_string (str): The new format string.
                Supports {timestamp}, {level}, and {message} placeholders.
        """
        ...
    
    def set_log_level(self, level: LogLevel) -> Any:
        """
        Modify the logger's base log level at runtime.

        Args:
            level (LogLevel): The new base log level.
        """
        ...
    
    def data(self, data: object, unsafe: bool = ...) -> Any:
        """
        Enqueue data to be sent to the master logger.

        Args:
            data (object): A msgspec.Struct representing the data.
            unsafe (bool, optional): If True, skips type checking on data for performance.
                Only use when you're certain all data objects are msgspec.Structs. Defaults to False.

        Raises:
            TypeError: If data is not a msgspec.Struct and type checking is enabled.
        """
        ...
    
    def trace(self, msg: str) -> Any:
        """
        Send a trace-level log message.

        Args:
            msg (str): The log message text.
        """
        ...
    
    def debug(self, msg: str) -> Any:
        """
        Send a debug-level log message.

        Args:
            msg (str): The log message text.
        """
        ...
    
    def info(self, msg: str) -> Any:
        """
        Send an info-level log message.

        Args:
            msg (str): The log message text.
        """
        ...
    
    def warning(self, msg: str) -> Any:
        """
        Send a warning-level log message.

        Args:
            msg (str): The log message text.
        """
        ...
    
    def error(self, msg: str) -> Any:
        """
        Send an error-level log message.

        Args:
            msg (str): The log message text.
        """
        ...
    
    def critical(self, msg: str) -> Any:
        """
        Send a critical-level log message.

        Args:
            msg (str): The log message text.
        """
        ...
    
    def shutdown(self) -> Any:
        """
        Flush any remaining messages and shuts down the worker logger.

        This method drains both the log buffer and the data buffer, sending any 
        remaining items to the master logger, and then stops the connection.

        Warning:
            After calling `shutdown()`, this logger should not be used again.
        """
        ...
    
    def is_running(self) -> bool:
        """
        Check if the master logger is running.
        """
        ...
    
    def get_name(self) -> str:
        """
        Get the name of the master logger.
        """
        ...
    
    def get_config(self) -> LoggerConfig:
        """
        Get the configuration of the master logger.
        """
        ...
    


