from __future__ import annotations

from collections.abc import AsyncIterator, Coroutine, Iterator
from typing import Any, Generic, TypeVar

T = TypeVar("T")

class GenericRingBuffer(Generic[T]):
    def __init__(self, max_capacity: int, disable_async: bool = False) -> None: ...
    def raw(self, copy: bool = True) -> list[T]: ...
    def unwrapped(self) -> list[T]: ...
    def overwrite_latest(self, item: T, increment_count: bool = False) -> None: ...
    def insert(self, item: T) -> None: ...
    def insert_batch(self, items: list[T]) -> None: ...
    def contains(self, item: T) -> bool: ...
    def consume(self) -> T: ...
    def consume_all(self) -> list[T]: ...
    def consume_iterable(self) -> Iterator[T]: ...
    def aconsume(self) -> Coroutine[Any, Any, T]: ...
    def aconsume_iterable(self) -> AsyncIterator[T]: ...
    def peekright(self) -> T: ...
    def peekleft(self) -> T: ...
    def clear(self) -> None: ...
    def is_empty(self) -> bool: ...
    def is_full(self) -> bool: ...
    def __contains__(self, item: T) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> T: ...
