from __future__ import annotations

from collections.abc import AsyncIterator, Coroutine, Iterable
from typing import Any

type Item = bytes | memoryview | bytearray

class IPCRingBufferConfig:
    path: str
    backlog: int
    num_producers: int
    num_consumers: int

    def __init__(
        self, path: str, backlog: int, num_producers: int, num_consumers: int
    ) -> None: ...
    @classmethod
    def default(cls) -> IPCRingBufferConfig: ...
    def should_producer_bind(self) -> bool: ...

class IPCRingBufferProducer:
    def __init__(self, config: IPCRingBufferConfig) -> None: ...
    def insert(self, item: Item, copy: bool = True) -> None: ...
    def insert_batch(self, items: Iterable[Item], copy: bool = True) -> None: ...
    def insert_packed(self, batch: Iterable[Item], copy: bool = True) -> None: ...
    def stop(self) -> None: ...

class IPCRingBufferConsumer:
    def __init__(self, config: IPCRingBufferConfig) -> None: ...
    def consume(self) -> Item: ...
    def consume_all(self) -> list[Item]: ...
    def consume_packed(self) -> list[Item]: ...
    def aconsume(self) -> Coroutine[Any, Any, Item]: ...
    def aconsume_packed(self) -> Coroutine[Any, Any, list[Item]]: ...
    def stop(self) -> None: ...
    def __aiter__(self) -> AsyncIterator[Item]: ...
    async def __anext__(self) -> Item: ...
