"""
This type stub file was generated by cyright.
"""

from typing import Any

from numpy import ndarray

class RingBufferMulti:
    """
    A fixed-size circular buffer supporting up to 2D shapes.
    """
    def __init__(self, shape: object, dtype: object) -> None:
        """
        Initialize the circular buffer with a specified shape and dtype.

        Args:
            shape (int or tuple of int): The shape of the buffer. For a 1D buffer,
                this can be a single integer (the capacity). For a 2D buffer,
                use (capacity, sub_array_length). Shapes with more than 2D
                are not supported.
            dtype (numpy.dtype or type): The dtype (or coercible type) for the buffer.
                Must be numeric, string, or bytes sub-dtype in NumPy.

        Raises:
            ValueError: If shape has more than 2 dimensions or capacity is <= 0.
            TypeError: If shape is not int, tuple, or list, or if dtype is unsupported.
        """
        ...
    
    def raw(self) -> ndarray:
        """
        Create a copy of the entire buffer array.

        Returns:
            np.ndarray: A copy of the internal buffer (including unused capacity).
        """
        ...
    
    def unsafe_raw(self) -> ndarray:
        """
        Return a direct view of the underlying buffer array without copying.

        Returns:
            np.ndarray: A NumPy array sharing memory with the buffer.

        Warning:
            Modifying the returned array also changes the buffer's internal state.
        """
        ...
    
    def unwrapped(self) -> ndarray:
        """
        Return the buffer contents in logical order (oldest to newest).

        Returns:
            np.ndarray: A copy of the buffer's data from oldest to newest.
        """
        ...
    
    def unsafe_write(self, value: object, insert_idx: int = ...) -> Any:
        """
        Write a value directly into the buffer at the current right index.

        Args:
            value (object): The value to write. Must be compatible with the buffer's dtype.
            insert_idx (Py_ssize_t, optional): For 2D buffers, which sub-array index to write from.

        Warning:
            This does not check buffer capacity or update indices. Use `unsafe_push` afterward.
        """
        ...
    
    def unsafe_push(self) -> Any:
        """
        Advance the right index after an `unsafe_write`.

        Warning:
            Overwrites the oldest data if the buffer is full. This does not check capacity.
        """
        ...
    
    def append(self, value: object) -> Any:
        """
        Append a new element (scalar or 1D array) to the buffer.

        Args:
            value (object): If the buffer is 1D, this should be a scalar. For a 2D buffer,
                this should be a 1D array-like of length `sub_array_len`.

        Raises:
            TypeError: If `value` cannot be cast to the buffer's dtype.
            ValueError: If `value` has invalid shape or length for a 2D buffer.
        """
        ...
    
    def popright(self) -> object:
        """
        Remove and return the most recently appended element.

        Returns:
            object: The last stored value.

        Raises:
            IndexError: If the buffer is empty.
        """
        ...
    
    def popleft(self) -> object:
        """
        Remove and return the oldest element in the buffer.

        Returns:
            object: The first stored value.

        Raises:
            IndexError: If the buffer is empty.
        """
        ...
    
    def reset(self) -> ndarray:
        """
        Clear the buffer and return its contents in logical order before clearing.

        Returns:
            cnp.ndarray: The data in the buffer (unwrapped) prior to reset.
        """
        ...
    
    def fast_reset(self) -> Any:
        """
        Quickly clear the buffer without returning old data.
        """
        ...
    
    def is_full(self) -> bool:
        """
        Check if the buffer is currently full.

        Returns:
            bool: True if buffer size == capacity, False otherwise.
        """
        ...
    
    def is_empty(self) -> bool:
        """
        Check if the buffer is empty.

        Returns:
            bool: True if size == 0, False otherwise.
        """
        ...
    
    def __contains__(self, other: object): # -> bool:
        """
        Check whether a given value is stored in the buffer.

        Args:
            other (object): The value to search for. Must be compatible with the buffer's dtype and shape.

        Returns:
            bool: True if found, False otherwise.
        """
        ...
    
    def __iter__(self): # -> Generator[Any, None, None]:
        """
        Yield elements in logical order from oldest to newest.

        Yields:
            object: Each element in the buffer.
        """
        ...
    
    def __len__(self): # -> int:
        """
        Get the number of elements currently in the buffer.

        Returns:
            int: The current size of the buffer.
        """
        ...
    
    def __getitem__(self, idx: int):
        """
        Access an element by logical index.

        Args:
            idx (int): The position of the desired element, where 0 is the oldest.

        Returns:
            object: The element at the specified index.

        Raises:
            IndexError: If the index is out of range.
        """
        ...
    


