from __future__ import annotations

from collections.abc import AsyncIterator, Coroutine, Iterator
from typing import Any

import numpy as np

class NumericRingBuffer:
    def __init__(
        self, max_capacity: int, dtype: np.dtype | type, disable_async: bool = False
    ) -> None: ...
    def raw(self, copy: bool = True) -> np.ndarray: ...
    def unwrapped(self) -> np.ndarray: ...
    def overwrite_latest(
        self, item: int | float, increment_count: bool = False
    ) -> None: ...
    def insert(self, item: int | float) -> None: ...

    # Accepts any 1-D numpy array of numeric dtype; runtime enforces dtype compatibility
    def insert_batch(self, items: np.ndarray) -> None: ...
    def contains(self, item: int | float) -> bool: ...
    def consume(self) -> int | float: ...
    def consume_all(self) -> np.ndarray: ...
    def consume_iterable(self) -> Iterator[int | float]: ...
    def aconsume(self) -> Coroutine[Any, Any, int | float]: ...
    def aconsume_iterable(self) -> AsyncIterator[int | float]: ...
    def peekright(self) -> int | float: ...
    def peekleft(self) -> int | float: ...
    def clear(self) -> None: ...
    def is_empty(self) -> bool: ...
    def is_full(self) -> bool: ...
    def __contains__(self, item: object) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> int | float: ...
