"""
This type stub file was generated by cyright.
"""

from typing import Any

from numpy import ndarray

class RingBufferOneDim:
    """
    A 1-dimensional fixed-size circular buffer for floats/doubles.
    """
    def __init__(self, capacity: int) -> None:
        """
        Parameters:
            capacity (int): The maximum number of elements the buffer can hold.
        """
        ...

    def raw(self) -> ndarray:
        """
        Return a copy of the internal buffer array.

        Returns:
            np.ndarray: A copy of the internal 1D NumPy array representing the buffer's contents.

        Note:
            The returned array includes all allocated space, not just the filled elements.
        """
        ...

    def unsafe_raw(self) -> ndarray:
        """
        Return a view of the internal buffer array without copying.

        Returns:
            np.ndarray: A NumPy array view of the buffer's internal data.

        Warning:
            Modifying the returned array may affect the buffer's internal state.
            Use with caution, as no copy is made.
        """
        ...

    def unwrapped(self) -> ndarray:
        """
        Return a copy of the buffer's contents in the correct (unwrapped) order.

        Returns:
            np.ndarray: A 1D NumPy array containing the buffer's data in order from oldest to newest.

        Tip:
            If you intend to iterate over the buffer in order for read only purposes,
            use `iter(self)` instead of `self.unwrapped()` for better performance.
        """
        ...

    def unsafe_write(self, value: float) -> Any:
        """
        Directly write a value to the buffer at the current right index without updating indices.

        Parameters:
            value (float): The float value to be added to the buffer.

        Warning:
            This method does not check if the buffer is full and does not update buffer indices.
            It is intended for use in conjunction with `unsafe_push`. Use with caution to avoid data corruption.
        """
        ...

    def unsafe_push(self) -> Any:
        """
        Advance the buffer indices after writing a value, without checking for buffer fullness.

        Warning:
            This method assumes that a value has already been written to the buffer at the current right index.
            It updates the buffer indices accordingly. It does not check if the buffer is full.
            If the buffer is full, it will overwrite the oldest data. Use with caution to avoid data corruption.

        Note:
            This method is intended for use in conjunction with `unsafe_write` for performance
            optimization when you are certain that the buffer management is correct.
        """
        ...

    def append(self, value: float) -> Any:
        """
        Add a new element to the end of the buffer.

        Parameters:
            value (float): The float value to be added to the buffer.
        """
        ...

    def popright(self) -> float:
        """
        Remove and return the last element from the buffer.

        Returns:
            float: The last value in the buffer.

        Raises:
            IndexError: If the buffer is empty.
        """
        ...

    def popleft(self) -> float:
        """
        Remove and return the first element from the buffer.

        Returns:
            float: The first value in the buffer.

        Raises:
            IndexError: If the buffer is empty.
        """
        ...

    def reset(self) -> ndarray:
        """
        Clear the buffer and reset it to its initial state.

        Returns:
            np.ndarray: A copy of the buffer's contents before resetting.

        Note:
            This method returns the data that was in the buffer before the reset.
        """
        ...

    def fast_reset(self) -> Any:
        """
        Quickly reset the buffer to its initial state without returning data.

        Note:
            This method clears the buffer's contents and resets indices.
            It does not return the previous data.
        """
        ...

    def is_full(self) -> bool:
        """
        Check if the buffer is full.

        Returns:
            bool: True if the buffer is full, False otherwise.
        """
        ...

    def is_empty(self) -> bool:
        """
        Check if the buffer is empty.

        Returns:
            bool: True if the buffer is empty, False otherwise.
        """
        ...

    def __contains__(self, value: float):  # -> bool:
        """
        Check if a value is present in the buffer.

        Parameters:
            value (float): The value to search for.

        Returns:
            bool: True if the value is in the buffer, False otherwise.
        """
        ...

    def __iter__(self):  # -> Generator[__MemoryView__[double, Any], None, None]:
        """
        Iterate over the elements in the buffer in order from oldest to newest.

        Yields:
            float: Each value in the buffer.
        """
        ...

    def __len__(self):  # -> Py_ssize_t:
        """
        Get the number of elements currently in the buffer.

        Returns:
            int: The current size of the buffer.
        """
        ...

    def __getitem__(self, idx: int):  # -> __MemoryView__[double, Any]:
        """
        Get the element at the given index.

        Parameters:
            idx (int): The index of the element to retrieve.

        Returns:
            float: The value at the specified index.

        Raises:
            IndexError: If the index is out of range.
        """
        ...
