"""
This type stub file was generated by cyright.
"""

from typing import Any

class PoolQueue:
    def __init__(self, max_size: int = ...) -> None:
        """
        Initializes the PoolQueue with a specified maximum size.
        """
        ...
    
    def generate_hash(self, msg: bytes) -> int:
        """
        Generates a 64-bit hash for the given message using xxhash.
        """
        ...
    
    def is_unique(self, hash_value: int) -> bool:
        """
        Checks if the hash is unique (not already in the queue).
        """
        ...
    
    def is_empty(self) -> bool:
        """
        Checks if the queue is empty.
        """
        ...
    
    def put_item(self, item: bytes, hash_value: int) -> Any:
        """
        Adds an item to the queue if there is space. Raises IndexError
        if the queue is full.
        """
        ...
    
    def put_item_with_overwrite(self, item: bytes, hash_value: int) -> Any:
        """
        Adds an item to the queue, overwriting the oldest item if the queue
        is full.
        """
        ...
    
    def take_item(self) -> bytes:
        """
        Removes and returns the oldest item from the queue.
        Raises IndexError if the queue is empty.
        """
        ...
    
    def take_all(self) -> list[bytes]:
        """
        Empties the queue into a list and restarts all
        internal states.
        """
        ...
    
    def get_size(self) -> int:
        """
        Returns the current size of the queue.
        """
        ...
    


class WsPoolConfig:
    """
    Configuration for WebSocket connection eviction and latency measurement policies.

    Attributes
    ----------
    evict_interval_s : int
        The interval in seconds at which eviction conditions are checked.

    evict_events_threshold : int
        The number of events after which eviction conditions are checked.
    """
    def __init__(self, evict_interval_s: int = ..., evict_events_threshold: int = ...) -> None:
        ...
    


class WsPool:
    """
    Manages a pool of fast WebSocket connections.
    """
    def __init__(self, size: int, on_message: function, logger: object, config: WsPoolConfig = ...) -> None:
        ...
    
    async def _msg_ingress(self) -> None:
        """
        Ingests queue data and feeds it to a user-provided
        processing function.
        """
        ...
    
    async def _eviction_manager(self) -> None:
        """
        Enforces the config to evict slow connections.
        """
        ...
    
    async def _open_new_conn(self, url: str, on_connect: list[dict] = ...): # -> None:
        """
        Establishes a new WebSocket connection, adds it to the connection pool,
        and begins data ingestion.

        Parameters
        ----------
        url : str
            The WebSocket URL to connect to.

        on_connect : Optional[List[Dict]], optional
            List of payloads to send upon connecting (default is None).
        """
        ...
    
    async def open(self, url: str, on_connect: list[dict] = ...): # -> None:
        """
        Starts all WebSocket connections in the pool.

        Parameters
        ----------
        url : str
            The WebSocket URL to connect to.

        on_connect : Optional[List[Dict]], optional
            List of payloads to send upon connecting (default is None).
        """
        ...
    
    def send_data(self, msg) -> Any:
        """
        Sends a payload through all WebSocket connections in the pool.
        """
        ...
    
    def close(self) -> Any:
        """
        Shuts down all WebSocket connections and stops the eviction task.
        """
        ...
    


