"""Protocol definition for WebSocket client interfaces.

Allows duck-typing between WsPool and WsSingle so users can write
generic code that works with either a single connection or a pool.
"""

from typing import Any, Protocol, Self, runtime_checkable

from mm_toolbox.websocket.connection import ConnectionState, WsConnectionConfig


@runtime_checkable
class WebsocketClient(Protocol):
    """Protocol for WebSocket client interfaces."""

    async def __aenter__(self) -> Self: ...

    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

    def __aiter__(self) -> Self: ...

    async def __anext__(self) -> bytes: ...

    def send_data(self, msg: bytes, only_fastest: bool = True) -> None: ...

    def close(self) -> None: ...

    def get_state(self) -> ConnectionState: ...

    def get_config(self) -> WsConnectionConfig: ...

    def get_connection_count(self) -> int: ...

    def get_latency_ms(self) -> float: ...

    def get_seq_id(self) -> int: ...

    def set_on_connect(self, on_connect: list[bytes]) -> None: ...
