"""
This type stub file was generated by cyright.
"""

from picows.picows import WSListener
from typing import Any

class WsConnection(WSListener):
    """
    Websocket connection class that manages opening, sending, receiving,
    and closing a Websocket connection.

    Attributes:
        conn_id (int): Unique identifier for this connection.
        seq_id (int): Sequence ID for received frames, incremented for
            each inbound frame.
    """
    def __init__(self, conn_id: int) -> None:
        """
        Initializes a new Websocket connection.

        Args:
            conn_id (int): Unique connection identifier (e.g., an incrementing ID).
        """
        ...

    def _timed_operations(self) -> Any:
        """
        Performs timed operations for the connection.
        """
        ...

    async def _attempt_reconnect(self):  # -> None:
        """
        Attempts to reconnect to the websocket server with exponential backoff.
        """
        ...

    async def open(
        self, url: str, on_connect: list[bytes], process_ws_frame: object
    ):  # -> None:
        """
        Opens a Websocket connection to the specified URL.

        Args:
            url (str): The Websocket URL to connect to.
            on_connect (list of bytes, optional): Messages to send immediately
                after connection is established.
            process_ws_frame (callable): A callback to handle received frames.
                The signature should be:
                `process_ws_frame(conn_id: int, seq_id: int, recv_time_ns: float, data: bytes)`
        """
        ...

    async def __aenter__(self):  # -> Self@WsConnection:
        """
        Async context manager entry point.

        Opens the Websocket connection if it is not already open.
        """
        ...

    async def __aexit__(self, exc_type, exc_val, exc_tb):  # -> None:
        """
        Async context manager exit point.

        Closes the Websocket connection if it is open.
        """
        ...
